# Generated by Django 3.0.1 on 2019-12-28 23:35

import apps.sig_health.models
from django.db import migrations, models
import django.utils.timezone
import django_enumfield.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', django_enumfield.db.fields.EnumField(default=0, enum=apps.sig_health.models.UniqueRowIDEnum, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=100, verbose_name='#sig-헬스 채널 ID')),
                ('oauth_access_token', models.CharField(max_length=100, verbose_name='botuser oauth token')),
                ('admit_emoji', models.CharField(blank=True, default='kr_admit', max_length=100, verbose_name='운동 인정 이모지')),
                ('regular_member_emoji', models.CharField(blank=True, default='star2', max_length=100, verbose_name='정회원 이모지')),
                ('minimum_admit_emoji_num', models.SmallIntegerField(blank=True, default=1, help_text='이 횟수 이상 유저에게 이모지가 찍혀야 운동으로 인정됩니다.', verbose_name='최소 인정 이모지 횟수')),
                ('minimum_regular_member_workout_num', models.SmallIntegerField(blank=True, default=4, help_text='일주일에 이 이상 운동하면 정회원으로 등극합니다.', verbose_name='정회원 최소 주별 운동 수')),
                ('regular_member_minimum_week', models.SmallIntegerField(blank=True, default=3, help_text='설정한 주 동안은 운동을 채우지 못해도 정회원으로 남습니다.', verbose_name='정회원 최소 근속 주수')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
