# Generated by Django 3.0.1 on 2019-12-29 00:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sig_health', '0002_member_workout_workoutadmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCheer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('week_count', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
