# Generated by Django 3.0.1 on 2019-12-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig_health', '0003_workoutcheer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_slack_id',
            new_name='slack_id',
        ),
    ]
