# Generated by Django 3.0.1 on 2019-12-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_health', '0004_auto_20191229_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
    ]
