# Generated by Django 3.0.1 on 2020-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_health', '0005_auto_20191229_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_hard_mode',
            field=models.BooleanField(default=False, help_text='자체 하드 모드 여부'),
        ),
    ]
