# Generated by Django 3.0.1 on 2020-01-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_health', '0006_member_is_hard_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='regular_member_minimum_week',
        ),
        migrations.AddField(
            model_name='meta',
            name='hard_mode_minimum_regular_member_workout_num',
            field=models.SmallIntegerField(blank=True, default=5, help_text='하드모드 정회원은 일주일에 이 이상 운동하면 정회원으로 등극합니다.', verbose_name='하드모드 정회원 최소 주별 운동 수'),
        ),
    ]
