# Generated by Django 3.0.1 on 2019-12-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_outbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emojitask',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='messagetask',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='replytask',
            managers=[
            ],
        ),
    ]
